# Generated by Django 5.2.1 on 2025-05-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
